#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';
require_once __DIR__ . '/autoloader.php';

use App\Bootstrap;

$bootstrap = new Bootstrap(false);
$application = $bootstrap->getConsoleApplication();
$application->run();
